language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install
  - cp config/local.config.php.dist config/local.sandbox.config.php

script:
  - cd tests/
  - ./../vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --bootstrap bootstrap.php
