<?php

defined('ZD_TESTS_TICKET_FIELD_SAMPLE_ID') || define('ZD_TESTS_TICKET_FIELD_SAMPLE_ID', 24154862);
defined('ZD_TESTS_USER_FIELD_SAMPLE_ID') || define('ZD_TESTS_USER_FIELD_SAMPLE_ID', 40262);
defined('ZD_TESTS_ORGANIZATION_FIELD_SAMPLE_ID') || define('ZD_TESTS_ORGANIZATION_FIELD_SAMPLE_ID', 39231);
