<?php

defined('ZD_TESTS_TICKET_FIELD_SAMPLE_ID') || define('ZD_TESTS_TICKET_FIELD_SAMPLE_ID', 22051480);
defined('ZD_TESTS_USER_FIELD_SAMPLE_ID') || define('ZD_TESTS_USER_FIELD_SAMPLE_ID', 34704);
defined('ZD_TESTS_ORGANIZATION_FIELD_SAMPLE_ID') || define('ZD_TESTS_ORGANIZATION_FIELD_SAMPLE_ID', 35240);
